[theme]
base = "dark"
primaryColor = "#67DDD2"
backgroundColor = "#090E16"
secondaryBackgroundColor = "#111C2A"
textColor = "#F2F7F7"
font = "sans serif"
[client]
toolbarMode = "viewer"
[server]
headless = true
[browser]
gatherUsageStats = false
